name: TownyMayors
version: '${version}'
main: dev.ua.ikeepcalm.townymayors.TownyMayors
api-version: '1.21'
depend:
  - Towny
permissions:
  limit.1:
    description: Allows adding players to the graylist
    default: false
  limit.2:
    description: Allows adding players from the graylist
    default: false
commands:
  grantwealth:
    description: Grants wealth node to a player
  removewealth:
    description: Removes wealth node from a player
  getchunklimit:
    description: Gets a town chunk limit of a player
  setchunklimit:
    description: Sets a town chunk limit of a player to selected value
  removechunklimit:
    description: Removes all townymayors.limit nodes of a player