name: TownyMayors
version: '${version}'
main: dev.ua.ikeepcalm.townymayors.TownyMayors
api-version: '1.21'
depend:
  - Towny
  - LuckPerms
description: Provides town tax reductions and free town management actions for players with special permissions.
author: ikeepcalm
commands:
  townymayors:
    description: Main command for TownyMayors plugin
    usage: /townymayors reload
    aliases: [tm]
    permission: townymayors.admin
permissions:
  townymayors.sponsor.wealth:
    description: Provides basic town benefits
    default: false
  townymayors.sponsor.astral:
    description: Provides enhanced town benefits
    default: false
  townymayors.sponsor.omega:
    description: Provides premium town benefits
    default: false
  townymayors.sponsor.eternal:
    description: Provides complete town benefits
    default: false
  townymayors.admin:
    description: Provides access to admin commands
    default: op
